package model;

public class Item {
    private int itemId;
    private String itemName;
    private int categoryId;
    private int quantity;
    private int supplierId;
    private double unitPrice;
    private int reorderLevel;
    
    // Constructors
    public Item() {
    }
    
    public Item(int itemId, String itemName, int categoryId, int quantity, int supplierId, double unitPrice, int reorderLevel) {
        this.itemId = itemId;
        this.itemName = itemName;
        this.categoryId = categoryId;
        this.quantity = quantity;
        this.supplierId = supplierId;
        this.unitPrice = unitPrice;
        this.reorderLevel = reorderLevel;
    }
    
    // For creating new items (ID will be auto-generated by the database)
    public Item(String itemName, int categoryId, int quantity, int supplierId, double unitPrice, int reorderLevel) {
        this.itemName = itemName;
        this.categoryId = categoryId;
        this.quantity = quantity;
        this.supplierId = supplierId;
        this.unitPrice = unitPrice;
        this.reorderLevel = reorderLevel;
    }
    
    // Getters and Setters
    public int getItemId() {
        return itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    
    public String getItemName() {
        return itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    
    public int getCategoryId() {
        return categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    
    public int getQuantity() {
        return quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    
    public int getSupplierId() {
        return supplierId;
    }
    
    public void setSupplierId(int supplierId) {
        this.supplierId = supplierId;
    }
    
    public double getUnitPrice() {
        return unitPrice;
    }
    
    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }
    
    public int getReorderLevel() {
        return reorderLevel;
    }
    
    public void setReorderLevel(int reorderLevel) {
        this.reorderLevel = reorderLevel;
    }
    
    // Helper methods
    public boolean isLowStock() {
        return quantity <= reorderLevel;
    }
    
    public boolean isOutOfStock() {
        return quantity <= 0;
    }
    
    @Override
    public String toString() {
        return "Item [itemId=" + itemId + ", itemName=" + itemName + ", categoryId=" + categoryId + ", quantity=" + quantity
                + ", supplierId=" + supplierId + ", unitPrice=" + unitPrice + ", reorderLevel=" + reorderLevel + "]";
    }
} 