package model;

public class User {
    private int userId;
    private String username;
    private String password;
    private String fullname;
    private String role;  // "ADMIN" or "STAFF"
    
    // Constructors
    public User() {
    }
    
    public User(int userId, String username, String password, String fullname, String role) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.fullname = fullname;
        this.role = role;
    }
    
    // For creating new users (ID will be auto-generated by the database)
    public User(String username, String password, String fullname, String role) {
        this.username = username;
        this.password = password;
        this.fullname = fullname;
        this.role = role;
    }
    
    // Getters and Setters
    public int getUserId() {
        return userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    public String getUsername() {
        return username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    public String getPassword() {
        return password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    public String getFullname() {
        return fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    
    public String getRole() {
        return role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    
    public boolean isAdmin() {
        return "ADMIN".equals(role);
    }
    
    @Override
    public String toString() {
        return "User [userId=" + userId + ", username=" + username + ", fullname=" + fullname + ", role=" + role + "]";
    }
} 